# Docker image to use.
image:

# Include access-control rules.
rbac:
  create: true

# Base CSI images and versions.
k8scsi:
  kubeletPath: "/var/lib/kubelet"
  baseRepo: "k8s.gcr.io/sig-storage"
  images:
    externalAttacher:
      image: "csi-attacher"
      tag: "v3.3.0"
    nodeDriverRegistrar:
      image: "csi-node-driver-registrar"
      tag: "v2.3.0"
