apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-h3-example
  labels:
    name: data-h3-example
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  storageClassName: h3
  csi:
    driver: csi-h3
    volumeHandle: data-id
    volumeAttributes:
      storageType: "redis"
      storageConfig: "127.0.0.1:6379"
      bucket: "b1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-h3-example
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: h3
  selector:
    matchLabels:
      name: data-h3-example
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-example
  labels:
    run: nginx-example
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx-example
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: data-h3-example
  volumes:
  - name: data-h3-example
    persistentVolumeClaim:
      claimName: data-h3-example
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-example
  labels:
    run: nginx-example
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: nginx-example
