apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-h3-example
  labels:
    name: data-h3-example
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  storageClassName: h3
  csi:
    driver: csi-h3
    volumeHandle: data-id
    volumeAttributes:
      storageUri: "redis://redis.default.svc:6379"
      bucket: "b1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-h3-example
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: h3
  selector:
    matchLabels:
      name: data-h3-example
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-example
  labels:
    run: nginx-example
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx-example
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: data-h3-example
  volumes:
  - name: data-h3-example
    persistentVolumeClaim:
      claimName: data-h3-example
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-example
  labels:
    run: nginx-example
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: nginx-example
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-config
data:
  filebrowser.json: |
    {
      "port": 80,
      "baseURL": "",
      "address": "",
      "log": "stdout",
      "database": "/database.db",
      "root": "/data"
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: filebrowser-example
  labels:
    run: filebrowser-example
spec:
  containers:
  - image: filebrowser/filebrowser
    imagePullPolicy: Always
    name: filebrowser-example
    ports:
    - containerPort: 80
      protocol: TCP
    args: ["--noauth"]
    volumeMounts:
    - name: filebrowser-config-volume
      mountPath: /.filebrowser.json
      subPath: filebrowser.json
    - name: data-h3-example
      mountPath: /data
  volumes:
  - name: filebrowser-config-volume
    configMap:
      name: filebrowser-config
      defaultMode: 0644
  - name: data-h3-example
    persistentVolumeClaim:
      claimName: data-h3-example
---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser-example
  labels:
    run: filebrowser-example
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: filebrowser-example
