# This YAML file contains attacher & csi driver API objects that are necessary
# to run external CSI attacher for H3

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-controller-h3
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: "csi-controller-h3"
  replicas: 1
  selector:
    matchLabels:
      app: csi-controller-h3
  template:
    metadata:
      labels:
        app: csi-controller-h3
    spec:
      serviceAccountName: csi-controller-h3
      containers:
        - name: csi-attacher
          {{- with .Values.k8scsi}}
          image: "{{ .baseRepo }}/{{ .images.externalAttacher.image }}:{{ .images.externalAttacher.tag }}"
          {{- end}}
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          # imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-cluster-driver-registrar
          {{- with .Values.k8scsi}}
          image: "{{ .baseRepo }}/{{ .images.clusterDriverRegistrar.image }}:{{ .images.clusterDriverRegistrar.tag }}"
          {{- end}}
          args:
            - "--v=5"
            - "--pod-info-mount-version=\"v1\""
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: h3
          image: {{- if .Values.image }} {{ .Values.image }} {{- else }} carvicsforth/csi-h3:v{{ .Chart.Version }} {{- end }}
          args :
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://plugin/csi.sock
          # imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /plugin
      volumes:
        - name: socket-dir
          emptyDir:
