kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: h3
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
provisioner: kubernetes.io/no-provisioner
