# This YAML file contains RBAC API objects that are necessary to run external
# CSI attacher for H3 adapter

apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-controller-h3
  namespace: csi-h3
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: external-controller-h3
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["csi.storage.k8s.io"]
    resources: ["csinodeinfos"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-attacher-role-h3
subjects:
  - kind: ServiceAccount
    name: csi-controller-h3
    namespace: csi-h3
roleRef:
  kind: ClusterRole
  name: external-controller-h3
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-cluster-driver-registrar-role-h3
rules:
  - apiGroups: ["csi.storage.k8s.io"]
    resources: ["csidrivers"]
    verbs: ["create", "delete"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "list", "watch", "delete"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-cluster-driver-registrar-binding-h3
subjects:
  - kind: ServiceAccount
    name: csi-controller-h3
    namespace: csi-h3
roleRef:
  kind: ClusterRole
  name: csi-cluster-driver-registrar-role-h3
  apiGroup: rbac.authorization.k8s.io